[15.0][ADD] partner_fax, partner_contact_gender
qrtl/rmm-oca pull request #32
Opened 2023-10-16 03:46 UTC by AungKoKoLin1997

2023-10-16 08:32 UTC, yostashiro approved these changes

2023-10-17 03:26 UTC, kanda999 requested changes
@AungKoKoLin1997 
`partner_contact_gender` module depends on `partner_contact_personal_information_page`
Can you add that module?
And to avoid this type of communication, try it in your environment at least once when creating a PR.

2023-10-17 03:43 UTC, kanda999 approved these changes
Thank you Lin!

2023-12-01 07:40 UTC, kanda999 commented
Translations of `partner_contact_personal_information_page` (V15, V16) were done yesterday at Weblate.
This time it is before it is reflected in the OCA, but I would like to manually add the translations and merge this PR.

2023-12-01 07:40 UTC, merged