[3829][15.0] [UPD] dotfiles
qrtl/rmm-oca pull request #35
Opened 2023-11-01 10:15 UTC by liuhehe1995

[3829](https://www.quartile.co/web#id=3829&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

2023-11-09 05:00 UTC, AungKoKoLin1997 requested changes

2023-11-09 05:00 UTC, AungKoKoLin1997 commented on website_odoo_debranding/templates/disable_odoo.xml
> +  </template>
Why did these changes? Is there any reason not to follow the adjustments from OCA?
https://github.com/OCA/website/commit/ea8f7775093b0b65d67e3037150c236cf5c8cfa7

2023-11-09 05:00 UTC, AungKoKoLin1997 commented on web_m2x_options/__init__.py
> +# from . import tests
Just remove it.

2023-11-09 05:26 UTC, liuhehe1995 commented on website_odoo_debranding/templates/disable_odoo.xml
> +  </template>
When I run pre-commit run --all-files, there is a prompt asking me to change this line.
`website_odoo_debranding/templates/disable_odoo.xml:11 Dangerous use of "replace" from view with priority `20 < 99`. Only replace as a last resort. Try position="attributes", position="move" or t-if="False" first - [xml-dangerous-qweb-replace-low-priority]`
<img width="905" alt="image" src="https://github.com/qrtl/rmm-oca/assets/147494891/9668a1c4-e9ca-49e4-af26-f9b9326a318c">

2023-11-09 07:31 UTC, liuhehe1995 commented on web_m2x_options/__init__.py
> +# from . import tests
Thank you,Removed.

2023-11-09 07:40 UTC, liuhehe1995 commented on website_odoo_debranding/templates/disable_odoo.xml
> +  </template>
I understood. 
I should change line 9 `priority="20"` to `priority="999"`

2023-11-13 10:41 UTC, liuhehe1995 commented on website_odoo_debranding/templates/disable_odoo.xml
> +  </template>
I made a mistake. The priority should be 99. not 999.
Created a new Commit to fix it.

2023-11-14 01:28 UTC, AungKoKoLin1997 commented on .copier-answers.yml
> +odoo_test_flavor: Both
Please adjust to be the same with other xxx-oca repos

2023-11-21 01:25 UTC, AungKoKoLin1997 reviewed
@liuhehe1995  Please run `copier update` again. The dotfiles are not latest anymore.

2023-11-21 03:51 UTC, AungKoKoLin1997 approved these changes

2023-11-21 04:17 UTC, yostashiro approved these changes

2023-11-21 04:17 UTC, merged